### ISSUE TITLE
Calendar is not updated 

### ISSUE THREAD

**Issue by aliMalik103** [year-calendar/rc-year-calendar#3]
Calendar is not updated first time when we delete the event. Second time we update some other day, previous one is updated.
There is some issue with calendar data source binding with the calendar component.

**Comment by MichiLor** [comment]
Is there any update on this issue?

**Comment by Paul-DS** [comment]
It seems to work on this example: https://codepen.io/Paul-DS/pen/wOpyNq
Could you provide a codepen/jsfiddle example with the bug ?

**Comment by MichiLor** [comment]
This bug occurs in your reference example as well for me. Try the following steps:
1. Add a new event
2. Delete this new event
     Outcome: event is still displayed
3. Add another event
     first event is removed
     second event is added

Obviously I want remove the event immediately after the delete event.
Any solution?

**Comment by Paul-DS** [comment]
Fixed in v1.0.2.

Thank you for your feedback !
