### ISSUE TITLE
Calendar doesn't refresh itself after deleting the event

### ISSUE THREAD

**Issue by SergeiAlekseenko** [year-calendar/rc-year-calendar#9]
Steps to repro:
1. Create event for a day
2. Delete event by submenu >Delete
Calendar doesn't refresh the date.

**Comment by Paul-DS** [comment]
Duplicate, see #3 

The bug is fixed in v1.0.2.

Thank you for your feedback

**Comment by SergeiAlekseenko** [comment]
The issue is fixed, confirmed.  
Thank you! The calendar is awesome.
